language: perl
perl:
  - "5.10"
sudo: false
before_script:
  - coverage-setup
script:
  - cd t/
  - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -l -j$(test-jobs) .
  - cover
after_success:
  - coverage-report
  - cover -report coveralls
