language: perl
perl:
  - "5.12"
sudo: false
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
install:
  - cpan-install --deps       # installs prereqs, including recommends
  - cpan-install --coverage   # installs converage prereqs, if enabled
  - cpan-install --quiet --notest Devel::Cover::Report::Coveralls
  - cpan-install 'Bio::Seq' 'Bio::SeqIO' 'File::Slurp' 'Findid::Utility' 'GetSeq' 'JSON' 'MIME::Lite' 'Test::MockObject' 'UR' 'WWW::Mechanize' 'YAML' 
before_script:
  - coverage-setup
script:
  - cd t/
  - PERL5OPT=-Mdevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -l -j$(test-jobs) .
  - cover
after_success:
  - coverage-report
  - cover -report coveralls
