language: perl
perl:
  - "5.10"
sudo: false
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
install:
  - cpan-install --deps       # installs prereqs, including recommends
  - cpan-install --coverage   # installs converage prereqs, if enabled
  - cpan-install --quiet --notest Devel::Cover::Report::Coveralls
  - cpan-install 'https://github.com/genome/UR.git' # install UR from github
before_script:
  - coverage-setup
script:
  - cd t/
  - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -l -j$(test-jobs) .
  - cover
after_success:
  - coverage-report
  - cover -report coveralls
